### ISSUE TITLE
Attempting to stand up highway-sdk node, process panics with "panic: account "alice" does not exist"

### ISSUE THREAD

**Issue by joshLong145** [sonr-io/sonr#185]
#### Issue description

When standing up highway the process panics with the error: "panic: account "alice" does not exist"

#### Steps to reproduce the issue

1. 
2. Start highway-sdk

#### What's the expected result?

* Highway starts up, establishing connections to chain.

#### What's the actual result?

Chain connection is unable to start, due to account query not successful

### Notes

Root cause is linked to initialization operations of the highway module in operations relating to establishing link to cosmos. once connection is established, there is an attempt to resolve a static account name from the ctx passed through during stand up. the account name is valid and can be confirmed to exist. however, upon loading debug symbols it can be observed a "keychain".

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1202528620406598/1202534272530083) by [Unito](https://www.unito.io)

**Comment by ntindle** [comment]
Workaround: specify `--home ~/.sonr` when creating Alice account

**Comment by joshLong145** [comment]
> Workaround: specify `--home ~/.sonr` when creating Alice account

has this been added to the readme / docs (didnt look first sorry)

**Comment by joshLong145** [comment]
issue has been resolved, moving to closed
