### ISSUE TITLE
Integrate IPFS as a library in Highway

### ISSUE THREAD

**Issue by prdlk** [sonr-io/sonr#239]
Utilize this [tutorial](https://github.com/ipfs/go-ipfs/blob/master/docs/examples/go-ipfs-as-a-library/main.go) in order to return the uploaded data hashes back from IPFS.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1202528620406598/1202529474215676) by [Unito](https://www.unito.io)

**Comment by prdlk** [comment]
Put Design for IPFS here @Peyton232

**Comment by Peyton232** [comment]
[IPFS internal library .pdf](https://github.com/sonr-io/highway-sdk/files/8414858/IPFS.internal.library.pdf)

**Comment by joshLong145** [comment]
Design has been reviewed and comments/considerations sent out
