### ISSUE TITLE
Motor Library with Highway Methods

### ISSUE THREAD

**Issue by ntindle** [sonr-io/sonr#264]
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1202528620406598/1202529400944406) by [Unito](https://www.unito.io)

**Comment by prdlk** [comment]
Implement Highway API interaction methods for Motor Node
`AccessApp()`
`InteractBucket()`
`InteractObject()`
`ListenChannel()`
`LinkDevice()`
`LinkPeer()`
`ReadBucket()`
`ReadObject()`
`RequestPeer()`
`RespondPeer()`
`Open()` - Method returns a stream of all p2p realtime events and opens node to network for interaction
