### ISSUE TITLE
[Refactor] Refactor host implementation to provide fallback in the cases where all connection options fail

### ISSUE THREAD

**Issue by joshLong145** [sonr-io/sonr#336]
When configuring a host instance which binds to libP2P we can get into a case where stand up operations never resolve and leave the host in an infinite cycle.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1202528620406598/1202534197572556) by [Unito](https://www.unito.io)

**Comment by prdlk** [comment]
Can you show code?
