### ISSUE TITLE
[LOGIC]: Migration from Memory store to FS Store provided in "IPLD-Prime" pkg

### ISSUE THREAD

**Issue by joshLong145** [sonr-io/sonr#347]
**Overview**
Migrate IPFS storage provider from an in memory model to leveraging the file system of the host.
`ipld-prime` has implementation for the following storage providers

* memory
* sharding
* fs

For now we should migrate from `memory` to `fs` as to keep information stored by users persisted upon application restarts
**Note**: IPFS light might not provide support for file system storage providers, we instead will transition to running full IPFS nodes in the highway to accommodate the file system storage provider.

**Sequence**
Steps involved in the logic sequence:

1. Migrate MemoryStore struct in `storage.go` in the `Highway` module within `internal` to no longer point at the inMemoryStore implementation to FileSystemDataStore.

* Struct should be renamed from `MemoryStore` to `FileSystemStore` to better reflect implementation.
* `FileSystemStore` should be implemented from the described interface [here](https://pkg.go.dev/github.com/ipfs/go-datastore@v0.5.1#PersistentDatastore)
  ** Acceptance Criteria **
* user uploaded files are stored on a highway node's file system. at a static directory path  (uploaded from `/v1/blob/upload` endpoint on highway).
* Highway node should be able to restart, and still have the ability to query by "CID" for an uploaded piece of content.
* Said content should then be looked up from disk, by the new store implementation, after restart of the node.
* 

**Resources**
Additional reading to help understand this proposal.

* https://github.com/ipld/go-ipld-prime
* https://pkg.go.dev/github.com/ipfs/go-datastore@v0.5.1#PersistentDatastore

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1202528620406598/1202529370406789) by [Unito](https://www.unito.io)

**Comment by mcurr10** [comment]
https://docs.google.com/document/d/1Kb8gi6FJVDRja8qR4bHU6EuDocI4hf5oQi4cHWiMojM/edit?usp=sharing
my working log of this assigment

**Comment by drgomesp** [comment]
As discussed internally, we're now working on designing a storage API that's agnostic to IPFS or any other specific storage implementation. The goal is to be able to have a generic API for storage which can accept blobs (the way we currently do) and understand CIDs at a high-level.

One of the possibilities discussed was the usage of Filecoin for the underlying storage implementation, which is something I'm currently also looking into, to understand a little bit more about the potential differences between this and the IPFS-specific version of the API.

Another thing I'm looking into is storing signed and encrypted data on IPFS through the usage of the new standards dag-jose and EIP-2844.

**References**:
- https://blog.ceramic.network/how-to-store-signed-and-encrypted-data-on-ipfs/
- https://eips.ethereum.org/EIPS/eip-2844
- https://github.com/ceramicnetwork/js-dag-jose
