### ISSUE TITLE
Rescaffold objects -> Schema module

### ISSUE THREAD

**Issue by ntindle** [sonr-io/sonr#352]
Rescaffold the module,  needs a genesis object with a `SchemaMap`.

Dependencies from cosmos include:

* Capability
* Bank

REF: *https://docs.cosmos.network/main/modules/*

Acceptance Criteria

* Remove the Object module
* Add Schema module
* Add Schema type struct
* Add CRUD request type structs

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1202528620406598/1202534190425162) by [Unito](https://www.unito.io)

**Comment by drgomesp** [comment]
3
