### ISSUE TITLE
Implement Schema Query Methods

### ISSUE THREAD

**Issue by ntindle** [sonr-io/sonr#353]
we will need to be able to query for `Schemas` by the following parameters:

* GetSchemaAll,
* GetSchemaByLabel
* GetSchemaByDID

Implementation of the above query methods should be within `x/schema/keeper/grpc_query_schema.go`

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1202528620406598/1202529370122452) by [Unito](https://www.unito.io)

**Comment by mcurr10** [comment]
I understand autogenerated implementation, however which area of the highway?
