### ISSUE TITLE
Wasm build fails due to compatibility issues on dependencies

### ISSUE THREAD

**Issue by drgomesp** [sonr-io/sonr#394]
Currently our WASM build is failing due to some compatibility issues of some of the dependencies.

An example is `goleveldb/leveldb`, which currently lacks support for WASM, which breaks the build. Other projects face the same issue, such as go-ethereum: https://github.com/ethereum/go-ethereum/issues/16192.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1202528620406598/1202529467439181) by [Unito](https://www.unito.io)

**Comment by ntindle** [comment]
https://github.com/syndtr/goleveldb/pull/288

**Comment by drgomesp** [comment]
One of the proposed solutions, I think from @mcjcloud, was to make the WASM build have its own entrypoint file (main.go), which would allow us to specify only the strictly required dependencies and potentially not have this error, since apparently goleveldb is one of the deps that are actually not being used (not sure which entrypoint though).

Another solution would be to isolate the goleveldb as some sort of a driver implementation, which would be hidden by an interface that we could introduce to represent the storage or whatever operations we want to do that require goleveldb or any other package. In this case, WASM could use something lighter or a native API instead of goleveldb.

**Comment by joshLong145** [comment]
> One of the proposed solutions, I think from @mcjcloud, was to make the WASM build have its own entrypoint file (main.go), which would allow us to specify only the strictly required dependencies and potentially not have this error, since apparently goleveldb is one of the deps that are actually not being used (not sure which entrypoint though).
> 
> Another solution would be to isolate the goleveldb as some sort of a driver implementation, which would be hidden by an interface that we could introduce to represent the storage or whatever operations we want to do that require goleveldb or any other package. In this case, WASM could use something lighter or a native API instead of goleveldb.

The  problem with the isolated entry point is that the type libs we are importing with some of our packages do infact depend on `goleveldb` due to some choices in implementation.  I think the current path forward is to isolate the types we are using to strictly their proto generations as its own pkg within our repository until they are able to implemented bindings for file system support.
