### ISSUE TITLE
Broken pagination on bucket/where_is

### ISSUE THREAD

**Issue by tgfassina** [sonr-io/sonr#554]
When I try to get buckets passing in a pagination limit number I get no results. Check this link:
http://v1-beta.sonr.ws:1317/sonr-io/sonr/bucket/where_is?pagination.limit=1000

However, if I omit that parameter then I get a list of buckets just fine
http://v1-beta.sonr.ws:1317/sonr-io/sonr/bucket/where_is

**Comment by joshLong145** [comment]
So does the response give a success response or are you getting an error message of some sort when attempting this operation with pagination values?

**Comment by tgfassina** [comment]
It gives a normal response but without any results

**Comment by ntindle** [comment]
Fixed in #564
