### ISSUE TITLE
Implement Schema by creator in Rest API

### ISSUE THREAD

**Issue by tgfassina** [sonr-io/sonr#610]
Running into trouble on `/sonr-io/sonr/schema/query/what_is/{creator}`.

I can't get any results using this endpoint. Check image:

![image](https://user-images.githubusercontent.com/1557361/191104375-2486b94a-09cd-4a0e-8247-e45896918824.png)
url: http://v1-beta.sonr.ws:1317/sonr-io/sonr/schema/query/what_is/snr1ar7860rcyr8k7rmk3zk7lfpl4fsdht8254m8rs

But that creator does have a few schemas:

![image](https://user-images.githubusercontent.com/1557361/191104755-f4d722ed-daad-4f04-85fc-fadc709f91de.png)
url: http://v1-beta.sonr.ws:1317/sonr-io/sonr/schema/query/all_schemas

I couldn't get any other response, regardless of creator or schema setup

**Comment by joshLong145** [comment]
'QueryWhatIsByCreator(req mt.QueryWhatIsByCreatorRequest)' is the endpoint on the motor api for this functionality. if you need this implemented in the binding layer of the api you should wrap it in the binding layer of speedway and create a route to access over http.

**Comment by ntindle** [comment]
You should be using “did:snr:” like the creator address specifies. 

v1-beta.sonr.ws:1317/sonr-io/sonr/schema/query/what_is/did:snr:1ar7860rcyr8k7rmk3zk7lfpl4fsdht8254m8rs

That will get you past this problem but it’s not implemented on the rest api side. 

Also, this is available through the motor directly.
