### ISSUE TITLE
Refactor Identity Controller to use Accumulators and Witnesses

### ISSUE THREAD

**Issue by prdlk** [sonr-io/sonr#889]
[SNR-127 Refactor Accumulator x/identity ORM System](https://linear.app/sonrhq/issue/SNR-127/refactor-accumulator-xidentity-orm-system)

**Comment by prnk28** [comment]
https://linear.app/sonrhq/issue/SNR-127/[sonr-21]-refactor-identity-controller-to-use-accumulators-and

**Comment by prdlk** [comment]
<p><a href="https://linear.app/sonrhq/issue/SNR-127/refactor-accumulator-xidentity-orm-system">SNR-127 Refactor Accumulator x/identity ORM System</a></p>
